### ISSUE TITLE
dataset 확인사항

### ISSUE THREAD

**Issue by Lucete28** [Lucete28/Sign_Language_Remaster#2]
Daily - Page 1~4 까지 길이가  이후에 비해 짧음
(speed관련 코드 재작성 과정에서 변화 생긴듯? 아마 천천히 넘기면서 프레임을 잘 잡는다던가 아니면 뭔가 두세번씩 잡히던가)

**Comment by Lucete28** [comment]
Daily - Page 1~4 까지 길이가 이후에 비해 짧음
(speed관련 코드 재작성 과정에서 변화 생긴듯? 아마 천천히 넘기면서 프레임을 잘 잡는다던가 아니면 뭔가 두세번씩 잡히던가)

**Comment by Lucete28** [comment]
Daily - Page 6에 하다 끊김

**Comment by Lucete28** [comment]
전체적으로 번역이 잘못된 부분있음 해결법 강구해야함

**Comment by Lucete28** [comment]
google_translate 라이브러리 멈추는 경우 있음
```
Traceback (most recent call last):
  File "c:/Users/oem/Desktop/jhy/signlanguage/Sign_Language_Remaster/code/lstm/run_generator.py", line 112, in <module>
    get_response()
  File "c:/Users/oem/Desktop/jhy/signlanguage/Sign_Language_Remaster/code/lstm/run_generator.py", line 87, in get_response
    make_data(item['title'],item['subDescription'] )
  File "c:\Users\oem\Desktop\jhy\signlanguage\Sign_Language_Remaster\code\lstm\data_generator.py", line 32, in make_data
    ACTION = trans_to_english(act_ko) # cv2 출력 문제로 영어로 변경
  File "c:\Users\oem\Desktop\jhy\signlanguage\Sign_Language_Remaster\code\lstm\data_generator.py", line 18, in trans_to_english
    result = translator.translate(text, src='ko', dest='en')
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\googletrans\client.py", line 194, in translate
    data, response = self._translate(text, dest, src)
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\googletrans\client.py", line 120, in _translate
    r = self.client.post(url, params=params, data=data)
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 824, in post
    return self.request(
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 600, in request
    return self.send(
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 620, in send
    response = self.send_handling_redirects(
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 647, in send_handling_redirects
    response = self.send_handling_auth(
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 684, in send_handling_auth
    response = self.send_single_request(request, timeout)
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 714, in send_single_request
    ) = transport.request(
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\connection_pool.py", line 152, in request
    response = connection.request(
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\connection.py", line 78, in request
    return self.connection.request(method, url, headers, stream, timeout)
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\http2.py", line 118, in request
    return h2_stream.request(method, url, headers, stream, timeout)
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\http2.py", line 292, in request
    status_code, headers = self.receive_response(timeout)
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\http2.py", line 344, in receive_response
    event = self.connection.wait_for_event(self.stream_id, timeout)
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\http2.py", line 197, in wait_for_event
    self.receive_events(timeout)
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_sync\http2.py", line 204, in receive_events
    data = self.socket.read(self.READ_NUM_BYTES, timeout)
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_backends\sync.py", line 62, in read
    return self.sock.recv(n)
_exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\oem\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore._exceptions.ReadTimeout: The read operation timed out
```
